version: '3.8'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

  api-server:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "5000:5000"
